name: React counter deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branch: [ master ]

jobs:
  build:
    runs-on: self-hosted

  steps:
    - uses: actions/checkout@v2
    - name: Use nodeJS ${{ matrix.node_version }}
      with:
        node_version: ${{ matrix.node_version }}
      run: |
        cd /home/aldrk/react-counter
        git pull origin master
        yarn install
        yarn build
        echo "Successfully deployed"
