name: Deploy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  deploy:
    strategy:
      matrix:
        node: [18.16.0]
      name: Node ${{ matrix.node }} sample

    steps:
      - uses: actions/checkout@v3
      - uses: appleboy/ssh-action@master
      - name: Deploy to Server
        with:
          node-version: ${{ matrix.version }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: "cd /home/aldrk/react-counter && git pull && yarn install && yarn build"
